version: '3.3'
services:
  gateway:
    image: 'api-mgmt/gateway:${docker-compose.api-mgmt.gateway.version}'
    container_name: gateway
    environment:
      - >-
        APIMAN_GATEWAY_OPTS=-Dapiman.es.host=${ELASTICSEARCH_HOST}
        -Dapiman.es.protocol=https
        -Dapiman.es.port=${ELASTICSEARCH_PORT}
        -Dapiman.es.timeout=10000
        -Dapiman.es.username=${ELASTICSEARCH_USERNAME}
        -Dapiman.es.password=${ELASTICSEARCH_PASSWORD}
        -Dapiman.truststore-password=${TRUSTSTORE_KEYSTORE_PASSWORD}
        -Dapiman.public-endpoint=${ENDPOINT}
        -Dkeycloak.host=${KEYCLOAK_HOST}
        -Dkeycloak.port=${KEYCLOAK_PORT}
        -Dkeycloak.realm=apiman
        -DallowSelfSigned=${SELF_SIGNED}
        -DallowAnyHost=${SELF_SIGNED}
        -Dkeycloak.realm-public-key=${KEYCLOAK_REALM_PUBLIC_KEY}
        -Dkeycloak.gateway.secret=${KEYCLOAK_GATEWAY_SECRET}
        -Dverticles.https.port=${GATEWAY_PORT}
        -DcachingPolicy.maxCacheSize=${MAX_CACHE_SIZE_IN_MB}
        -Dapiman.gateway-backend-keystore=${KEYSTORE_TRUSTSTORE_PATH:-}${GATEWAY_BACKEND_KEYSTORE:-/usr/src/apiman/apiman-distro-vertx/certs/apiman.jks}
        -Dapiman.gateway-backend-truststore=${KEYSTORE_TRUSTSTORE_PATH:-}${GATEWAY_BACKEND_TRUSTSTORE:-}
        -Dapiman.gateway-es-keystore=${KEYSTORE_TRUSTSTORE_PATH:-}${GATEWAY_ES_KEYSTORE:-/usr/src/apiman/apiman-distro-vertx/certs/apiman.jks}
        -Dapiman.gateway-es-truststore=${KEYSTORE_TRUSTSTORE_PATH:-}${GATEWAY_ES_TRUSTSTORE:-/usr/src/apiman/apiman-distro-vertx/certs/apiman.jks}
        -Dapiman.gateway-client-keystore=${KEYSTORE_TRUSTSTORE_PATH:-}${GATEWAY_CLIENT_KEYSTORE:-/usr/src/apiman/apiman-distro-vertx/certs/apiman.jks}
        -Dapiman.gateway-client-truststore=${KEYSTORE_TRUSTSTORE_PATH:-}${GATEWAY_CLIENT_TRUSTSTORE:-/usr/src/apiman/apiman-distro-vertx/certs/apiman.jks}
        -Dapiman.gateway-keycloak-keystore=${KEYSTORE_TRUSTSTORE_PATH:-}${GATEWAY_KEYCLOAK_KEYSTORE:-/usr/src/apiman/apiman-distro-vertx/certs/apiman.jks}
        -Dapiman.gateway-keycloak-truststore=${KEYSTORE_TRUSTSTORE_PATH:-}${GATEWAY_KEYCLOAK_TRUSTSTORE:-/usr/src/apiman/apiman-distro-vertx/certs/apiman.jks}
        -Dapiman.gateway-allowedProtocols=${TLS_ALLOWED_PROTOCOLS:-}
        -Dallowed_cors_origins=https://${UI_HOST}:${UI_PORT},https://${UI_HOST}:${DEV_PORTAL_PORT}
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
      - '${GATEWAY_MANAGEMENT_PORT}:8081'
    volumes:
      - type: volume
        source: gateway_logs
        target: /usr/src/apiman/apiman-distro-vertx/logs
      - type: bind
        source: ./../../configs
        target: ${KEYSTORE_TRUSTSTORE_PATH:-/usr/src/apiman/apiman-distro-vertx/certs}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
    restart: always
volumes:
  gateway_logs:
    driver: local
