version: '3'
services:
  mysql:
    image: 'mysql:${docker-compose.api-mgmt.mysql.version}'
    container_name: mysql
    environment:
      - 'MYSQL_DATABASE=keycloak'
      - 'MYSQL_USER=keycloak'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - 'mysql_logs:/var/log/mysql'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
    restart: always
  keycloak:
    image: 'api-mgmt/keycloak:${docker-compose.api-mgmt.keycloak.version}'
    container_name: keycloak
    environment:
      - 'DB_PASSWORD=${MYSQL_PASSWORD}'
      - 'KEYCLOAK_USER=${KEYCLOAK_ADMIN_USERNAME}'
      - 'KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}'
      - 'KEYCLOAK_IMPORT=/opt/api-mgmt/realm.json'
      - 'JDBC_PARAMS=useSSL=false' # No need for SSL between MySQL <-> Keycloak in a docker network
      # Following variables are used to create self-signed certificates
      - 'ENDPOINT=${ENDPOINT}'
      - 'TRUSTSTORE_KEYSTORE_PASSWORD=${TRUSTSTORE_KEYSTORE_PASSWORD}'
    ports:
      - '${KEYCLOAK_PORT}:8443'
    depends_on:
      - mysql
    volumes:
      - 'keycloak_logs:/opt/jboss/keycloak/standalone/log'
      - './../configs/tls.crt:/etc/x509/https/tls.crt'
      - './../configs/tls.key:/etc/x509/https/tls.key'
      # Following mount is used to create self-signed certificates
      - './../configs:/configs'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
    restart: always
  elasticsearch:
    image: 'elasticsearch:${docker-compose.api-mgmt.elasticsearch.version}'
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms${ELASTICSEARCH_JAVA_MEMORY} -Xmx${ELASTICSEARCH_JAVA_MEMORY}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096
    volumes:
      - 'elasticsearch_data:/usr/share/elasticsearch/data'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
    restart: always
  ui:
    image: 'api-mgmt/ui:${docker-compose.api-mgmt.ui.version}'
    container_name: ui
    environment:
      - >-
        CATALINA_OPTS=-Dbridge.url=${BRIDGE_URL}
        -Dapiman.es.protocol=http
        -Dapiman.es.port=9200
        -Dapiman.es.timeout=10000
        -Dapiman.es.host=elasticsearch
        -Dbridge.username=${BRIDGE_USERNAME}
        -Dbridge.password=${BRIDGE_PASSWORD}
        -Dbridge.port=${BRIDGE_PORT}
        -Dkeycloak.host=${ENDPOINT}
        -Dkeycloak.port=${KEYCLOAK_PORT}
        -Dkeycloak.truststore-password=${TRUSTSTORE_KEYSTORE_PASSWORD}
        -Dkeycloak.apiman.secret=${KEYCLOAK_APIMAN_SECRET}
        -Dkeycloak.apimanui.secret=${KEYCLOAK_APIMANUI_SECRET}
        -DkeystorePassword=${TRUSTSTORE_KEYSTORE_PASSWORD}
    ports:
      - '${UI_PORT}:8443'
    depends_on:
      - elasticsearch
      - keycloak
    volumes:
      - 'ui_logs:/usr/local/tomcat/logs'
      - './../configs/apiman.jks:/usr/local/tomcat/conf/apiman.jks'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
    restart: always
  gateway:
    image: 'api-mgmt/gateway:${docker-compose.api-mgmt.gateway.version}'
    container_name: gateway
    environment:
      - >-
        APIMAN_GATEWAY_OPTS=-Dapiman.es.host=elasticsearch
        -Dapiman.es.protocol=http
        -Dapiman.es.port=9200
        -Dapiman.es.timeout=10000
        -Dapiman.truststore-password=${TRUSTSTORE_KEYSTORE_PASSWORD}
        -Dapiman.public-endpoint=${ENDPOINT}
        -Dkeycloak.host=${ENDPOINT}
        -Dkeycloak.port=${KEYCLOAK_PORT}
        -DdevMode=${SELF_SIGNED}
        -DallowSelfSigned=${SELF_SIGNED}
        -DallowAnyHost=${SELF_SIGNED}
        -Dkeycloak.realm-public-key=${KEYCLOAK_REALM_PUBLIC_KEY}
        -Dkeycloak.gateway.secret=${KEYCLOAK_GATEWAY_SECRET}
        -Dverticles.https.port=${GATEWAY_PORT}
        -DcachingPolicy.maxCacheSize=${MAX_CACHE_SIZE_IN_MB}
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    depends_on:
      - elasticsearch
      - keycloak
    volumes:
      - 'gateway_logs:/usr/src/apiman/apiman-distro-vertx/logs'
      - './../configs/apiman.jks:/usr/src/apiman/apiman-distro-vertx/GatewayBackendKeystore.jks'
      - './../configs/apiman.jks:/usr/src/apiman/apiman-distro-vertx/GatewayBackendTruststore.jks'
      - './../configs/apiman.jks:/usr/src/apiman/apiman-distro-vertx/GatewayClientKeystore.jks'
      - './../configs/apiman.jks:/usr/src/apiman/apiman-distro-vertx/GatewayClientTruststore.jks'
      - './../configs/apiman.jks:/usr/src/apiman/apiman-distro-vertx/GatewayKeycloakTruststore.jks'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        mode: non-blocking
    restart: always
volumes:
  mysql_data:
    driver: local
  mysql_logs:
    driver: local
  keycloak_logs:
    driver: local
  elasticsearch_data:
    driver: local
  ui_logs:
    driver: local
  gateway_logs:
    driver: local